services:
  - type: web
    name: ruby-ocorrencias-bot
    runtime: node
    buildCommand: npm ci --only=production && npm run build
    startCommand: npm start
    plan: free
    region: oregon
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: TELEGRAM_WEBHOOK_URL
        value: https://ruby-ocorrencias-bot.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: PGDATABASE
        sync: false
      - key: PGHOST
        sync: false
      - key: PGPASSWORD
        sync: false
      - key: PGPORT
        sync: false
      - key: PGUSER
        sync: false